server.port=8082
spring.application.name=searchable-encryption-api
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB
server.error.include-message=always
ml.service.url=http://127.0.0.1:8001
ml.service.host=0.0.0.0
ml.service.port=8001
ml.service.working-dir=../ml-service
ml.service.python=.venv/Scripts/python.exe
ml.service.start-timeout-ms=15000
