package com.bdic.model;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Session information returned to the client after successful sign-in.
 *
 * <p>The current client keeps a long-lived connection to the server; sessionId is mainly used for server-side session management and UI debugging extensions.</p>
 */
public class SessionInfo implements Serializable {
    /** Java serialization version to keep session information compatible in object streams. */
    @Serial
    private static final long serialVersionUID = 1L;

    /** Random session ID generated by the server. */
    private final String sessionId;
    /** Username that owns the current session. */
    private final String username;
    /** Session expiration time, displayed in the client's local time zone. */
    private final LocalDateTime expiresAt;

    /**
     * Constructs session information returned to the client after successful sign-in.
     */
    public SessionInfo(String sessionId, String username, LocalDateTime expiresAt) {
        this.sessionId = sessionId;
        this.username = username;
        this.expiresAt = expiresAt;
    }

    /** Returns the server session ID. */
    public String getSessionId() {
        return sessionId;
    }

    /** Returns the currently signed-in username. */
    public String getUsername() {
        return username;
    }

    /** Returns the session expiration time. */
    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }
}
